version: "2.2"

services:
  ping-server:
    container_name: ping-server
    ports:
      - "8080:8080"
    build:
      dockerfile: src/Dockerfile
    image: ping:lastest
    restart: unless-stopped


  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

